// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDloMYbegF8CoC0JrnqM5wRooMM1peicc',
    appId: '1:689265101383:web:45748cd323ea3852f2ff62',
    messagingSenderId: '689265101383',
    projectId: 'campuskartt-6e635',
    authDomain: 'campuskartt-6e635.firebaseapp.com',
    storageBucket: 'campuskartt-6e635.appspot.com',
    measurementId: 'G-136PQVL415',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgIKCmF5lMGwvx40_wx3chp8ynyfqKIUE',
    appId: '1:689265101383:android:8c68f9d5b00a4ef7f2ff62',
    messagingSenderId: '689265101383',
    projectId: 'campuskartt-6e635',
    storageBucket: 'campuskartt-6e635.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXGYDVEb9xfv9adt3Mdgb_oO4bXA_ljDM',
    appId: '1:689265101383:ios:24263963427def37f2ff62',
    messagingSenderId: '689265101383',
    projectId: 'campuskartt-6e635',
    storageBucket: 'campuskartt-6e635.appspot.com',
    iosBundleId: 'com.example.campuskartt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXGYDVEb9xfv9adt3Mdgb_oO4bXA_ljDM',
    appId: '1:689265101383:ios:d78ad75b9040718bf2ff62',
    messagingSenderId: '689265101383',
    projectId: 'campuskartt-6e635',
    storageBucket: 'campuskartt-6e635.appspot.com',
    iosBundleId: 'com.example.campuskartt.RunnerTests',
  );
}
